name: Deploy Dolgins Storefront

on:
  push:
    branches:
      - main

jobs:
  build-check:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build Storefront
        run: yarn build

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-check
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build Storefront
        run: yarn build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/dolgins/dolgins/medusajs-2.0-for-railway-boilerplate/storefront1
            git pull origin main
            yarn install
            yarn build
            pm2 restart ecosystem.config.js

      - name: Notify Deployment Success
        run: echo "Deployment successful!"

      - name: Pipeline Deployment test
        run:  echo "Pipeline deployment test success!"