name: Deploy Dolgins Storefront

on:
  push:
    branches:
      - main
    paths:
      - "storefront1/**" 

jobs:
  build-check:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: storefront1/yarn.lock

      - name: Install Dependencies
        run: |
          cd storefront1
          yarn install

      - name: Build Storefront
        run: |
          cd storefront1
          yarn build

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-check
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd storefront1
          yarn install 

      - name: Build Storefront
        run: |
          cd storefront1
          yarn build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/dolgins/dolgins/medusajs-2.0-for-railway-boilerplate/storefront1
            git pull origin main
            yarn install 
            yarn build
            pm2 restart ecosystem.config.js

      - name: Notify Deployment Success
        run: echo "Deployment successful!"

      - name: Pipeline Deployment test
        run:  echo "Pipeline deployment test success!"
